## Exercise 1: NumPy: Create an array with values ranging from 50 to 100

In [2]:
import numpy as np
a = np.arange(50,101)
print(a)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

In [17]:
a = ([[1,1,1],
      [1,1,1],
      [1,1,1]])
print(a)
print(np.shape(a))
a = np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(a)

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
(3, 3)
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


## Exercise 3: Convert a list and tuple into arrays

In [23]:
lst = [1,2,3,4,5,6,7,8]
a = np.array(lst)
print(a)
tuple_a = ([8, 4, 6], [1, 2, 3])
b = np.asarray(tuple_a)
print(b)

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [28]:
import numpy as np
a = [ 0.,12.,45.21,34,99.91]
a = np.array(a)
print(a)
b = np.array(5*a/9 - 5*32/9)
print(b)

[ 0.   12.   45.21 34.   99.91]
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [43]:
a = np.array([1,2,3], dtype=np.float64)
print(a)
print(a.size)
print(a.itemsize)
print(a.nbytes)

[1. 2. 3.]
3
8
24


## Exercise 6: Get the unique elements of an array

In [45]:
a = np.array([10,10,20,20,30,30])
print(a)
a = np.unique(a)
print(a)


[10 10 20 20 30 30]
[10 20 30]


## Exercise 7: Change the dimension of an array


In [66]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
b = np.reshape(a,(3,3),order='C')
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [68]:
a = np.linspace(2.5,6.5,30)
print(a)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [75]:
a1 = np.array([10,20,30])
a2 = np.array([40,50,60])
a3 = np.column_stack((a1,a2))
print(a3)

[[10 40]
 [20 50]
 [30 60]]


## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [78]:
a = np.zeros((5,5))
print(a)
a += np.arange(5)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [88]:
a = np.arange(1,100)
print(a)

b= a[(a % 3 == 0) | (a % 5 == 0)]
print(b)
print(b.sum())


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [14]:
import numpy as np
x = np.arange(4)
print(x)
y = np.arange(8).reshape(2,4)
print(y)
for a, b in np.nditer([x,y]):
    print("%d:%d" % (a,b),)
    
    


[0 1 2 3]
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [28]:
a = np.array([[0.4243631,0.48558583,0.32924763],
              [0.7439979,0.58220701,0.38213418],
              [0.5097581,0.34528799,0.1563123 ]])
print(a)
a[a > .5] = .5

print(a)

[[0.4243631  0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
[[0.4243631  0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 14: Add a new row to an empty numpy array

In [43]:
a = np.empty((0,3),int)
print(a)
a = np.append(a,np.array([[10,20,30]]),axis=0)
a =np.append(a,np.array([[40,50,60]]),axis=0)
print(a)

[]
[[10 20 30]
 [40 50 60]]


## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

In [59]:
a = np.array([1,2,3])
b = np.array([2,3,4])
print(np.vstack((a,b)))
c = np.array([[1],[2],[3]])
d = np.array([[2],[3],[4]])
print(c)
print(d)
print(np.vstack((c,d)))

[[1 2 3]
 [2 3 4]]
[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
